//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoHang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryReceipt()
        {
            this.InventoryReceiptDetails = new HashSet<InventoryReceiptDetail>();
        }
    
        public int ReceiptID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryReceiptDetail> InventoryReceiptDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
